#'Original need: Move a subset of 388 large (half 1.2GB+ each, half 50MB each) out of a
#'multi-folder filetree containing ~2500 files of similar size.  
#'
#'Files are paired end fastq.gz and fastx identified only by a sample identifier common
#'across all sample-associated files and their suffixes.  Other file types included in
#'the folders of interest are .clipped.fastq.gz, .fastx.png, .txt, etc.
#'
#'We are providing a list of sample identifiers for which we'd like to transfer FASTQ and
#'FASTX filetypes.  The list source is a column in an imported .csv file renamed example.csv.



#Provide Inputs: Sample identifier list, source path, destination path

samplist <- read.csv(file="./example.csv")
specnm <- samplist$Specimen.Name
src <- "H:/"
pathto <- "G:/"

#'Select folders to iterate through when searching for files to copy.
#'NOTE: ignore.case=TRUE parameter required in Windows file structure only.

folderlist <- list.files("H:/", ignore.case=TRUE)
flfastq <- folderlist[grepl("FASTQs",folderlist)]    #All Folder names contained "FASTQs"
fastqtxt <- folderlist[grepl(".txt", folderlist)]    #Some accessory files contain "FASTQs.summary.txt"
flonly <- flfastq[!(flfastq %in% fastqtxt)]          #Select folder names only

#'Loop to iteratively copy by file name from source to destination
#'For loop possibly not preferred due to inefficiency; but rate limiting
#'step is file transfer rate in this application

k <- 1    #k loop: loops through foulders in 'src' file tree
i <- 1    #i loop: loops through criteria matching filenames within 'src/folder' defined by k
j <- 1    #j loop: copies files defined by i

for (k in 1:length(flonly)){
  
  #'Create list of files in src/flonly[k] folder and bind to list to be 
  #'iterated across in 'i' loop
  
  pathfrom <- paste(src, flonly[k],"/", sep="")
  filelist <- list.files(pathfrom, ignore.case=TRUE)
  
  for (i in 1:length(filelist)){
    
    #Grab all filenames containing specimen names, 'fastq' or fastx; removing 'clipped' and 'png'
    #Define subgroups
    specfiles <- filelist[grepl(specnm[i],filelist)]
    clipped <- specfiles[grepl("clipped",specfiles)]
    png <- specfiles[grepl("png", specfiles)]
    fastx <- specfiles[grepl("fastx", specfiles)]
    fastq <- specfiles[grepl("fastq.gz",specfiles)]
    
    #Create subsets containing only filenames of interest
    fastqnoclip <- fastq[!(fastq %in% clipped)]
    fastxnopng <- fastx[!(fastx %in% png)]
    nopng_clip <- fastxnopng[!(fastxnopng %in% clipped)]
    
    for (j in 1:length(fastqnoclip)){
      
      #Move files based on list generated by 'i' loop
    
      #Define source and destination paths for .fastq.gz, keeping original filename
      fullpathfrom <- paste(pathfrom, fastqnoclip[j], sep="")
      fullpathto <- paste(pathto, fastqnoclip[j], sep="")
      #copy fastq.gz files
      file.copy(fullpathfrom, fullpathto, copy.mode=FALSE)
      
      #Define source and destination paths for .fastx, keeping original filename
      fullpathxfrom <- paste(pathfrom, nopng_clip[j], sep="")
      fullpathxto <- paste(pathto, nopng_clip[j], sep="")
      #copy fastx files
      file.copy(fullpathxfrom, fullpathxto, copy.mode=FALSE)
      
      j <- j+1
    } 
    
    i <- i+1
  }
  
  k <- k+1
}
